//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayLifeSure.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutTranslation
    {
        public int TranslationId { get; set; }
        public Nullable<int> AboutId { get; set; }
        public string LanguageCode { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Description { get; set; }
        public string Bullet1 { get; set; }
        public string Bullet2 { get; set; }
        public string Bullet3 { get; set; }
    
        public virtual TblAbouts TblAbouts { get; set; }
    }
}
