//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayLifeSure.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfoTranslation
    {
        public int Id { get; set; }
        public int ContactInfoId { get; set; }
        public string LanguageCode { get; set; }
        public string Title { get; set; }
        public string Info { get; set; }
    
        public virtual TblContactInfo TblContactInfo { get; set; }
    }
}
