//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayLifeSure.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaqTranslation
    {
        public int TranslationId { get; set; }
        public int FaqId { get; set; }
        public string LanguageCode { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    
        public virtual TblFAQs TblFAQs { get; set; }
    }
}
