//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayLifeSure.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureTranslation
    {
        public int TranslationId { get; set; }
        public int FeatureId { get; set; }
        public string LanguageCode { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    
        public virtual TblFeatures TblFeatures { get; set; }
    }
}
