//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayLifeSure.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LifeSureDbEntities1 : DbContext
    {
        public LifeSureDbEntities1()
            : base("name=LifeSureDbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAbouts> TblAbouts { get; set; }
        public virtual DbSet<TblContactInfo> TblContactInfo { get; set; }
        public virtual DbSet<TblEmployees> TblEmployees { get; set; }
        public virtual DbSet<TblFAQs> TblFAQs { get; set; }
        public virtual DbSet<TblFeatures> TblFeatures { get; set; }
        public virtual DbSet<TblServices> TblServices { get; set; }
        public virtual DbSet<TblTestimonials> TblTestimonials { get; set; }
        public virtual DbSet<AboutTranslation> AboutTranslation { get; set; }
        public virtual DbSet<ServiceTranslation> ServiceTranslation { get; set; }
        public virtual DbSet<FeatureTranslation> FeatureTranslation { get; set; }
        public virtual DbSet<FaqTranslation> FaqTranslation { get; set; }
        public virtual DbSet<TestimonialTranslations> TestimonialTranslations { get; set; }
        public virtual DbSet<ContactInfoTranslation> ContactInfoTranslation { get; set; }
    }
}
