//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayLifeSure.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFeatures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFeatures()
        {
            this.FeatureTranslation = new HashSet<FeatureTranslation>();
        }
    
        public int FeatureId { get; set; }
        public string FeatureTitle { get; set; }
        public string FeatureDesc { get; set; }
        public string FeatureIcon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeatureTranslation> FeatureTranslation { get; set; }
    }
}
