//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayLifeSure.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFAQs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFAQs()
        {
            this.FaqTranslation = new HashSet<FaqTranslation>();
        }
    
        public int FAQId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaqTranslation> FaqTranslation { get; set; }
    }
}
