//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DayLifeSure.Models.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestimonialTranslations
    {
        public int Id { get; set; }
        public int TestimonialId { get; set; }
        public string LanguageCode { get; set; }
        public string FullName { get; set; }
        public string Profession { get; set; }
        public string Comment { get; set; }
    
        public virtual TblTestimonials TblTestimonials { get; set; }
    }
}
